version: '3'
services:
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    restart: unless-stopped
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  apm_server:
    build:
      context: apm/
    volumes:
      - ./apm/config/:/usr/share/apm/config:ro
    restart: unless-stopped
    ports:
      - "8181:8200"
    networks:
      - elk
    depends_on:
      - elasticsearch

  rabbitmq:
    container_name: myrabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
      - '1883:1883'
      - '15675:15675'
    image: 'rabbitmq:3'
    networks:
      - elk
  node-red-docker:
    restart: unless-stopped
    ports:
      - '1880:1880'
    container_name: mynodered
    image: nodered/node-red-docker
    networks:
      - elk

networks:

  elk:
    driver: bridge


